server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: loja
          uri: http://localhost:8080/
          predicates:
            - Path=/api/v1/compras/**

        - id: fornecedor
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/**

        - id: transportador
          uri: http://localhost:8083/
          predicates:
            - Path=api/v1/**